### ISSUE TITLE
setup.py imports six module which is not installed install time

### ISSUE THREAD

**Issue by gijzelaerr** [ratt-ru/meqtrees-cattery#95]
```
Collecting meqtrees-cattery>=1.5.1 (from DDFacet==0.4.0.0)
  Downloading https://files.pythonhosted.org/packages/fd/81/147f756ddab3183a13ed5e51edf61a372aebec0b50ebb12312b90b23d225/meqtrees_cattery-1.6.0.tar.gz (369kB)
    100% |████████████████████████████████| 378kB 9.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5cpIxc/meqtrees-cattery/setup.py", line 6, in <module>
        import six
    ImportError: No module named six
```

https://github.com/ska-sa/meqtrees-cattery/commit/dcf2ab34b0c2f9faf0d4c48850751c7c7b34508e#r32196889

**Comment by gijzelaerr** [comment]
This gives errors when you try to install cattery in an empty virtualenv, since six is not installed yet. Best ist just no not include any dependencies in your `setup.py` file for this reason. What you try to do can be solved using extra restrictions in your `install_requires` statement:

https://stackoverflow.com/questions/21082091/install-requires-based-on-python-version

**Comment by bennahugo** [comment]
ok will include a fix in the next round of PRs, busy py3ing timba

**Comment by bennahugo** [comment]
fixed
